package com.verumomnis.forensic.ui

import android.app.Application
import android.content.Context
import android.net.Uri
import android.provider.OpenableColumns
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.verumomnis.forensic.blockchain.BlockchainService
import com.verumomnis.forensic.blockchain.OpenTimestampsService
import com.verumomnis.forensic.core.Constitution
import com.verumomnis.forensic.core.ConstitutionalPrompt
import com.verumomnis.forensic.core.DeviceTier
import com.verumomnis.forensic.core.Llm
import com.verumomnis.forensic.core.ModelLoader
import com.verumomnis.forensic.crypto.VerificationResult
import com.verumomnis.forensic.identity.IdentityService
import com.verumomnis.forensic.engine.AntiHarassmentMonitor
import com.verumomnis.forensic.engine.AudioEvidence
import com.verumomnis.forensic.engine.EmailModule
import com.verumomnis.forensic.engine.EvidenceDocument
import com.verumomnis.forensic.engine.FindingsJsonEmitter
import com.verumomnis.forensic.engine.ForensicService
import com.verumomnis.forensic.engine.GuardianBrain
import com.verumomnis.forensic.engine.MediaEvidence
import com.verumomnis.forensic.engine.ReportGenerator
import com.verumomnis.forensic.engine.ScanResult
import com.verumomnis.forensic.engine.TaxModule
import com.verumomnis.forensic.model.ForensicReport
import com.verumomnis.forensic.model.GuardianAssessment
import com.verumomnis.forensic.model.GpsRecord
import com.verumomnis.forensic.model.ResearchFindings
import com.verumomnis.forensic.model.ResearchTrigger
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import com.verumomnis.forensic.model.HarassmentVerdict
import com.verumomnis.forensic.model.OtsAnchorResult
import com.verumomnis.forensic.model.OtsStatus
import com.verumomnis.forensic.model.SealedEmail
import com.verumomnis.forensic.ojrs.DeepResearchEngine
import com.verumomnis.forensic.ojrs.WebSearchService
import com.verumomnis.forensic.trust.TrustEngine
import com.verumomnis.forensic.trust.TrustScore
import com.verumomnis.forensic.pdf.SealedPdfExporter
import com.verumomnis.forensic.security.SilenceLedger
import com.verumomnis.forensic.seal.DocumentSealer
import com.verumomnis.forensic.seal.OpenTimestampsClient
import com.verumomnis.forensic.seal.SealMetadataCodec
import com.verumomnis.forensic.seal.SealVerifier
import com.verumomnis.forensic.vault.EvidenceVault
import com.verumomnis.forensic.work.ScanWorkScheduler
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.io.File
import java.time.Instant
import java.util.TimeZone
